### ISSUE TITLE
Precommit hook rejects valid .gitlab-ci.yml configuration

### ISSUE THREAD

**Issue by AlexanderWells-diamond** [dls-controls/dls-python3-skeleton#40]
It seems that the precommit hook rejects the ["Reference Tags"](https://docs.gitlab.com/ee/ci/yaml/yaml_optimization.html#reference-tags) feature in Gitlab-CI's YAML files. 

When it runs on a file attempting to use this syntax, I see this error:

```
Check Yaml...............................................................Failed
- hook id: check-yaml
- exit code: 1

could not determine a constructor for the tag '!reference'
  in ".gitlab-ci.yml", line 16, column 7
```

The snippet which breaks it:
```
include:
  - project: "controls/reports/ci_templates"
    ref: master
    file: "python3/dls_py3_template.yml"

tests_and_publish_coverage:
  before_script:
    - !reference [default, before_script]
    # We need this file to exist in the expected place for tests
    - mv src/pts_webserver/.env.example src/pts_webserver/.env
```

This syntax appears to be valid in Gitlab, as tested by pasting it into our Gitlab CI's inbuilt Linter.

**Comment by coretl** [comment]
https://github.com/pre-commit/pre-commit-hooks#check-yaml would suggest that adding `--unsafe` to the check-yaml hook will allow this

**Comment by coretl** [comment]
So I guess that would be
```yaml
...
      - id: check-yaml
        args: [--unsafe]
...
```
